<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>97707186-8c91-4c19-8662-5286fac43b3f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://den-signoff08.castlighthealth.com/v2/user_dashboard#icon__bell</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page_dashboard&quot;]/ikkuna[1]/div[@class=&quot;app&quot;]/div[@class=&quot;lo-top ng-star-inserted&quot;]/header[1]/ven-lo-header[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;lo-header ng-trigger ng-trigger-appFadeIn&quot;]/div[@class=&quot;lo-header__wrapper&quot;]/div[@class=&quot;lo-header__content&quot;]/nav[@class=&quot;lo-header__sitenav-wrapper&quot;]/ven-lo-sitenav[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;lo-sitenav&quot;]/div[@class=&quot;lo-sitenav__wrapper&quot;]/ul[@class=&quot;lo-sitenav__list ng-star-inserted&quot;]/li[@class=&quot;lo-sitenav__list-item ng-star-inserted&quot;]/a[@class=&quot;lo-sitenav__nav-link&quot;]/ven-util-icon[@class=&quot;lo-sitenav__notification-icon&quot;]/svg[@class=&quot;icon icon__bell ng-star-inserted&quot;]/use[1]</value>
   </webElementProperties>
</WebElementEntity>
