<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpendingOverview</name>
   <tag></tag>
   <elementGuidId>17a15fe7-7dff-4aeb-a430-5bb8ebd4201a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='startcontent']/div/ven-past-care-view/div/div[2]/div/ven-claims-overview/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>claims-overview__breakdown-table</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spending overview for 2019It can take 1-4 weeks after payment for claims to appear.Total fees billed$0.00Paid by Castlight$0.00Your responsibility $0.00Medical claims updated May 1, 2011</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startcontent&quot;)/div[@class=&quot;lo-main__wrapper&quot;]/ven-past-care-view[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;lo-main lo-main_past-care&quot;]/div[@class=&quot;lo-main__content lo-main__content_no-sidebar lo-main__content_past-care&quot;]/div[@class=&quot;past-care-view__content-wrapper ng-star-inserted&quot;]/ven-claims-overview[1]/div[@class=&quot;claims-overview ng-star-inserted&quot;]/div[@class=&quot;claims-overview__breakdown-table&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='startcontent']/div/ven-past-care-view/div/div[2]/div/ven-claims-overview/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ven-claims-overview/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
